name: Self-hosted runner test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Say Hello
        run: echo "Hello from self-hosted runner"

      - name: Show OS
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Finish
        run: echo "Success ðŸŽ‰"
