- name: Say Hello
  shell: pwsh
  run: |
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
    Write-Output "Hello from self-hosted runner"
    # If you want to run your script file, add this line:
    # ./_work/temp/b6bbbc1a-1cc1-4a79-9567-dr09d61abc08.ps1
